// Generated by sprite2spans — do not edit.
//
// Each frame is stored as per-row lists of solid horizontal spans in
// 12-bit R4G4B4.  A span is drawn by the app as either one RUN_COLOR word
// (possible only when every channel is 0x0 or 0xF) or a SET of
// cmp_held_fg followed by a RUN of held_fg; the header does not choose.
//
// Span budget checked at generation time: 6 per row.

#pragma once

#include <cstdint>

struct SpriteSpan
{
    uint16_t x;        // pixels from the frame's left edge
    uint16_t width;    // pixels, always >= 1
    uint16_t rgb444;   // 0x0RGB
};

struct SpriteRow
{
    uint16_t first;    // index into the frame's span array
    uint16_t count;    // spans in this row, 0 for a fully transparent row
};

struct SpriteFrame
{
    const char       *name;
    uint16_t          width;
    uint16_t          height;
    uint16_t          max_row_spans;
    const SpriteRow  *rows;    // `height` entries
    const SpriteSpan *spans;
};

inline constexpr int SPRITE_SPAN_BUDGET = 6;

// smurf_walk0 — 24x32, 56 spans, worst row 5
inline constexpr SpriteSpan SMURF_WALK0_SPANS[] = {
    {   8,   8, 0xFFF },   // row 0
    {   7,  10, 0xFFF },   // row 1
    {   6,  12, 0xFFF },   // row 2
    {   5,  14, 0xFFF },   // row 3
    {   4,  16, 0xFFF },   // row 4
    {   3,  18, 0xFFF },   // row 5
    {   3,  18, 0xFFF },   // row 6
    {   3,   6, 0xFFF }, {   9,   6, 0x6AE }, {  15,   6, 0xFFF },   // row 7
    {   3,   4, 0xFFF }, {   7,  10, 0x6AE }, {  17,   4, 0xFFF },   // row 8
    {   4,   2, 0xFFF }, {   6,  12, 0x6AE }, {  18,   2, 0xFFF },   // row 9
    {   5,  14, 0x6AE },   // row 10
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 11
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 12
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 13
    {   4,  16, 0x6AE },   // row 14
    {   5,  14, 0x6AE },   // row 15
    {   6,  12, 0x6AE },   // row 16
    {   7,  10, 0x6AE },   // row 17
    {   3,  18, 0x6AE },   // row 18
    {   3,  18, 0x6AE },   // row 19
    {   3,  18, 0x6AE },   // row 20
    {   3,  18, 0x6AE },   // row 21
    {   3,  18, 0x6AE },   // row 22
    {   3,  18, 0x6AE },   // row 23
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 24
    {   5,  14, 0xFFF },   // row 25
    {   5,  14, 0xFFF },   // row 26
    {   4,  16, 0xFFF },   // row 27
    {   4,   5, 0xFFF }, {  15,   5, 0xFFF },   // row 28
    {   4,   5, 0xFFF }, {  15,   5, 0xFFF },   // row 29
    {   3,   7, 0x000 }, {  14,   7, 0x000 },   // row 30
    {   3,   7, 0x000 }, {  14,   7, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURF_WALK0_ROWS[] = {
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  1 },
    {   7,  3 },
    {  10,  3 },
    {  13,  3 },
    {  16,  1 },
    {  17,  5 },
    {  22,  5 },
    {  27,  5 },
    {  32,  1 },
    {  33,  1 },
    {  34,  1 },
    {  35,  1 },
    {  36,  1 },
    {  37,  1 },
    {  38,  1 },
    {  39,  1 },
    {  40,  1 },
    {  41,  1 },
    {  42,  3 },
    {  45,  1 },
    {  46,  1 },
    {  47,  1 },
    {  48,  2 },
    {  50,  2 },
    {  52,  2 },
    {  54,  2 },
};
inline constexpr SpriteFrame SMURF_WALK0 = { "smurf_walk0", 24, 32, 5, SMURF_WALK0_ROWS, SMURF_WALK0_SPANS };

// smurf_walk1 — 24x32, 52 spans, worst row 5
inline constexpr SpriteSpan SMURF_WALK1_SPANS[] = {
    {   8,   8, 0xFFF },   // row 0
    {   7,  10, 0xFFF },   // row 1
    {   6,  12, 0xFFF },   // row 2
    {   5,  14, 0xFFF },   // row 3
    {   4,  16, 0xFFF },   // row 4
    {   3,  18, 0xFFF },   // row 5
    {   3,  18, 0xFFF },   // row 6
    {   3,   6, 0xFFF }, {   9,   6, 0x6AE }, {  15,   6, 0xFFF },   // row 7
    {   3,   4, 0xFFF }, {   7,  10, 0x6AE }, {  17,   4, 0xFFF },   // row 8
    {   4,   2, 0xFFF }, {   6,  12, 0x6AE }, {  18,   2, 0xFFF },   // row 9
    {   5,  14, 0x6AE },   // row 10
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 11
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 12
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 13
    {   4,  16, 0x6AE },   // row 14
    {   5,  14, 0x6AE },   // row 15
    {   6,  12, 0x6AE },   // row 16
    {   7,  10, 0x6AE },   // row 17
    {   3,  18, 0x6AE },   // row 18
    {   3,  18, 0x6AE },   // row 19
    {   3,  18, 0x6AE },   // row 20
    {   3,  18, 0x6AE },   // row 21
    {   3,  18, 0x6AE },   // row 22
    {   3,  18, 0x6AE },   // row 23
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 24
    {   5,  14, 0xFFF },   // row 25
    {   5,  14, 0xFFF },   // row 26
    {   5,  14, 0xFFF },   // row 27
    {   8,   8, 0xFFF },   // row 28
    {   8,   8, 0xFFF },   // row 29
    {   7,  10, 0x000 },   // row 30
    {   7,  10, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURF_WALK1_ROWS[] = {
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  1 },
    {   7,  3 },
    {  10,  3 },
    {  13,  3 },
    {  16,  1 },
    {  17,  5 },
    {  22,  5 },
    {  27,  5 },
    {  32,  1 },
    {  33,  1 },
    {  34,  1 },
    {  35,  1 },
    {  36,  1 },
    {  37,  1 },
    {  38,  1 },
    {  39,  1 },
    {  40,  1 },
    {  41,  1 },
    {  42,  3 },
    {  45,  1 },
    {  46,  1 },
    {  47,  1 },
    {  48,  1 },
    {  49,  1 },
    {  50,  1 },
    {  51,  1 },
};
inline constexpr SpriteFrame SMURF_WALK1 = { "smurf_walk1", 24, 32, 5, SMURF_WALK1_ROWS, SMURF_WALK1_SPANS };

// smurf_jump — 24x32, 54 spans, worst row 5
inline constexpr SpriteSpan SMURF_JUMP_SPANS[] = {
    {   8,   8, 0xFFF },   // row 0
    {   7,  10, 0xFFF },   // row 1
    {   6,  12, 0xFFF },   // row 2
    {   5,  14, 0xFFF },   // row 3
    {   4,  16, 0xFFF },   // row 4
    {   3,  18, 0xFFF },   // row 5
    {   3,  18, 0xFFF },   // row 6
    {   3,   6, 0xFFF }, {   9,   6, 0x6AE }, {  15,   6, 0xFFF },   // row 7
    {   3,   4, 0xFFF }, {   7,  10, 0x6AE }, {  17,   4, 0xFFF },   // row 8
    {   4,   2, 0xFFF }, {   6,  12, 0x6AE }, {  18,   2, 0xFFF },   // row 9
    {   5,  14, 0x6AE },   // row 10
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 11
    {   2,   6, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   6, 0x6AE },   // row 12
    {   2,   6, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   6, 0x6AE },   // row 13
    {   2,  20, 0x6AE },   // row 14
    {   2,  20, 0x6AE },   // row 15
    {   2,  20, 0x6AE },   // row 16
    {   2,   4, 0x6AE }, {   7,  10, 0x6AE }, {  18,   4, 0x6AE },   // row 17
    {   2,  20, 0x6AE },   // row 18
    {   2,  20, 0x6AE },   // row 19
    {   5,  14, 0x6AE },   // row 20
    {   5,  14, 0x6AE },   // row 21
    {   5,  14, 0x6AE },   // row 22
    {   5,  14, 0x6AE },   // row 23
    {   5,  14, 0xFFF },   // row 24
    {   5,  14, 0xFFF },   // row 25
    {   5,  14, 0xFFF },   // row 26
    {   5,  14, 0xFFF },   // row 27
    {   6,   5, 0xFFF }, {  13,   5, 0xFFF },   // row 28
    {   6,   5, 0xFFF }, {  13,   5, 0xFFF },   // row 29
    {   5,  14, 0x000 },   // row 30
    {   5,  14, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURF_JUMP_ROWS[] = {
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  1 },
    {   7,  3 },
    {  10,  3 },
    {  13,  3 },
    {  16,  1 },
    {  17,  5 },
    {  22,  5 },
    {  27,  5 },
    {  32,  1 },
    {  33,  1 },
    {  34,  1 },
    {  35,  3 },
    {  38,  1 },
    {  39,  1 },
    {  40,  1 },
    {  41,  1 },
    {  42,  1 },
    {  43,  1 },
    {  44,  1 },
    {  45,  1 },
    {  46,  1 },
    {  47,  1 },
    {  48,  2 },
    {  50,  2 },
    {  52,  1 },
    {  53,  1 },
};
inline constexpr SpriteFrame SMURF_JUMP = { "smurf_jump", 24, 32, 5, SMURF_JUMP_ROWS, SMURF_JUMP_SPANS };

// smurf_duck — 24x32, 53 spans, worst row 5
inline constexpr SpriteSpan SMURF_DUCK_SPANS[] = {
    {  10,   4, 0xFFF },   // row 5
    {   8,   8, 0xFFF },   // row 6
    {   7,  10, 0xFFF },   // row 7
    {   6,  12, 0xFFF },   // row 8
    {   5,  14, 0xFFF },   // row 9
    {   4,  16, 0xFFF },   // row 10
    {   3,  18, 0xFFF },   // row 11
    {   3,  18, 0xFFF },   // row 12
    {   3,   6, 0xFFF }, {   9,   6, 0x6AE }, {  15,   6, 0xFFF },   // row 13
    {   3,   4, 0xFFF }, {   7,  10, 0x6AE }, {  17,   4, 0xFFF },   // row 14
    {   4,   2, 0xFFF }, {   6,  12, 0x6AE }, {  18,   2, 0xFFF },   // row 15
    {   5,  14, 0x6AE },   // row 16
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 17
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 18
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 19
    {   4,  16, 0x6AE },   // row 20
    {   5,  14, 0x6AE },   // row 21
    {   6,  12, 0x6AE },   // row 22
    {   7,  10, 0x6AE },   // row 23
    {   3,  18, 0x6AE },   // row 24
    {   3,  18, 0x6AE },   // row 25
    {   3,  18, 0x6AE },   // row 26
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 27
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 28
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 29
    {   3,   2, 0x6AE }, {   5,  14, 0x000 }, {  19,   2, 0x6AE },   // row 30
    {   5,  14, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURF_DUCK_ROWS[] = {
    {   0,  0 },
    {   0,  0 },
    {   0,  0 },
    {   0,  0 },
    {   0,  0 },
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  1 },
    {   7,  1 },
    {   8,  3 },
    {  11,  3 },
    {  14,  3 },
    {  17,  1 },
    {  18,  5 },
    {  23,  5 },
    {  28,  5 },
    {  33,  1 },
    {  34,  1 },
    {  35,  1 },
    {  36,  1 },
    {  37,  1 },
    {  38,  1 },
    {  39,  1 },
    {  40,  3 },
    {  43,  3 },
    {  46,  3 },
    {  49,  3 },
    {  52,  1 },
};
inline constexpr SpriteFrame SMURF_DUCK = { "smurf_duck", 24, 32, 5, SMURF_DUCK_ROWS, SMURF_DUCK_SPANS };

// smurf_death — 24x32, 62 spans, worst row 5
inline constexpr SpriteSpan SMURF_DEATH_SPANS[] = {
    {   8,   8, 0xFFF },   // row 0
    {   7,  10, 0xFFF },   // row 1
    {   6,  12, 0xFFF },   // row 2
    {   5,  14, 0xFFF },   // row 3
    {   4,  16, 0xFFF },   // row 4
    {   3,  18, 0xFFF },   // row 5
    {   3,  18, 0xFFF },   // row 6
    {   3,   6, 0xFFF }, {   9,   6, 0x6AE }, {  15,   6, 0xFFF },   // row 7
    {   3,   4, 0xFFF }, {   7,  10, 0x6AE }, {  17,   4, 0xFFF },   // row 8
    {   4,   2, 0xFFF }, {   6,  12, 0x6AE }, {  18,   2, 0xFFF },   // row 9
    {   5,   2, 0x6AE }, {   7,   4, 0x000 }, {  11,   2, 0x6AE }, {  13,   4, 0x000 }, {  17,   2, 0x6AE },   // row 10
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 11
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 12
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 13
    {   4,   3, 0x6AE }, {   7,   4, 0x000 }, {  11,   2, 0x6AE }, {  13,   4, 0x000 }, {  17,   3, 0x6AE },   // row 14
    {   5,  14, 0x6AE },   // row 15
    {   6,  12, 0x6AE },   // row 16
    {   7,  10, 0x6AE },   // row 17
    {   6,  12, 0x6AE },   // row 18
    {   0,  24, 0x6AE },   // row 19
    {   0,  24, 0x6AE },   // row 20
    {   0,  24, 0x6AE },   // row 21
    {   5,  14, 0x6AE },   // row 22
    {   5,  14, 0x6AE },   // row 23
    {   5,  14, 0xFFF },   // row 24
    {   5,  14, 0xFFF },   // row 25
    {   5,  14, 0xFFF },   // row 26
    {   3,  18, 0xFFF },   // row 27
    {   3,   5, 0xFFF }, {  16,   5, 0xFFF },   // row 28
    {   3,   5, 0xFFF }, {  16,   5, 0xFFF },   // row 29
    {   2,   7, 0x000 }, {  15,   7, 0x000 },   // row 30
    {   2,   7, 0x000 }, {  15,   7, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURF_DEATH_ROWS[] = {
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  1 },
    {   7,  3 },
    {  10,  3 },
    {  13,  3 },
    {  16,  5 },
    {  21,  5 },
    {  26,  5 },
    {  31,  5 },
    {  36,  5 },
    {  41,  1 },
    {  42,  1 },
    {  43,  1 },
    {  44,  1 },
    {  45,  1 },
    {  46,  1 },
    {  47,  1 },
    {  48,  1 },
    {  49,  1 },
    {  50,  1 },
    {  51,  1 },
    {  52,  1 },
    {  53,  1 },
    {  54,  2 },
    {  56,  2 },
    {  58,  2 },
    {  60,  2 },
};
inline constexpr SpriteFrame SMURF_DEATH = { "smurf_death", 24, 32, 5, SMURF_DEATH_ROWS, SMURF_DEATH_SPANS };

// smurfette_walk0 — 24x32, 77 spans, worst row 5
inline constexpr SpriteSpan SMURFETTE_WALK0_SPANS[] = {
    {   7,  10, 0xFD4 },   // row 1
    {   4,  16, 0xFD4 },   // row 2
    {   2,  20, 0xFD4 },   // row 3
    {   2,  20, 0xFD4 },   // row 4
    {   1,  22, 0xFD4 },   // row 5
    {   1,  22, 0xFD4 },   // row 6
    {   2,   7, 0xFD4 }, {   9,   6, 0x6AE }, {  15,   7, 0xFD4 },   // row 7
    {   2,   5, 0xFD4 }, {   7,  10, 0x6AE }, {  17,   5, 0xFD4 },   // row 8
    {   4,   2, 0xFD4 }, {   6,  12, 0x6AE }, {  18,   2, 0xFD4 },   // row 9
    {   5,  14, 0x6AE },   // row 10
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 11
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 12
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 13
    {   1,   3, 0xFD4 }, {   4,  16, 0x6AE }, {  20,   3, 0xFD4 },   // row 14
    {   1,   4, 0xFD4 }, {   5,  14, 0x6AE }, {  19,   4, 0xFD4 },   // row 15
    {   1,   4, 0xFD4 }, {   6,  12, 0x6AE }, {  19,   4, 0xFD4 },   // row 16
    {   1,   4, 0xFD4 }, {   7,  10, 0x6AE }, {  19,   4, 0xFD4 },   // row 17
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 18
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 19
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 20
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 21
    {   3,   5, 0x6AE }, {   8,   8, 0xFFF }, {  16,   5, 0x6AE },   // row 22
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 23
    {   3,  18, 0xFFF },   // row 24
    {   2,  20, 0xFFF },   // row 25
    {   2,  20, 0xFFF },   // row 26
    {   2,  20, 0xFFF },   // row 27
    {   2,  20, 0xFFF },   // row 28
    {   3,   1, 0xFFF }, {   4,   5, 0x6AE }, {   9,   6, 0xFFF }, {  15,   5, 0x6AE }, {  20,   1, 0xFFF },   // row 29
    {   3,   7, 0x000 }, {  10,   4, 0xFFF }, {  14,   7, 0x000 },   // row 30
    {   3,   7, 0x000 }, {  10,   4, 0xFFF }, {  14,   7, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURFETTE_WALK0_ROWS[] = {
    {   0,  0 },
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  3 },
    {   9,  3 },
    {  12,  3 },
    {  15,  1 },
    {  16,  5 },
    {  21,  5 },
    {  26,  5 },
    {  31,  3 },
    {  34,  3 },
    {  37,  3 },
    {  40,  3 },
    {  43,  3 },
    {  46,  3 },
    {  49,  3 },
    {  52,  3 },
    {  55,  3 },
    {  58,  3 },
    {  61,  1 },
    {  62,  1 },
    {  63,  1 },
    {  64,  1 },
    {  65,  1 },
    {  66,  5 },
    {  71,  3 },
    {  74,  3 },
};
inline constexpr SpriteFrame SMURFETTE_WALK0 = { "smurfette_walk0", 24, 32, 5, SMURFETTE_WALK0_ROWS, SMURFETTE_WALK0_SPANS };

// smurfette_walk1 — 24x32, 73 spans, worst row 5
inline constexpr SpriteSpan SMURFETTE_WALK1_SPANS[] = {
    {   7,  10, 0xFD4 },   // row 1
    {   4,  16, 0xFD4 },   // row 2
    {   2,  20, 0xFD4 },   // row 3
    {   2,  20, 0xFD4 },   // row 4
    {   1,  22, 0xFD4 },   // row 5
    {   1,  22, 0xFD4 },   // row 6
    {   2,   7, 0xFD4 }, {   9,   6, 0x6AE }, {  15,   7, 0xFD4 },   // row 7
    {   2,   5, 0xFD4 }, {   7,  10, 0x6AE }, {  17,   5, 0xFD4 },   // row 8
    {   4,   2, 0xFD4 }, {   6,  12, 0x6AE }, {  18,   2, 0xFD4 },   // row 9
    {   5,  14, 0x6AE },   // row 10
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 11
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 12
    {   4,   4, 0x6AE }, {   8,   2, 0x000 }, {  10,   4, 0x6AE }, {  14,   2, 0x000 }, {  16,   4, 0x6AE },   // row 13
    {   1,   3, 0xFD4 }, {   4,  16, 0x6AE }, {  20,   3, 0xFD4 },   // row 14
    {   1,   4, 0xFD4 }, {   5,  14, 0x6AE }, {  19,   4, 0xFD4 },   // row 15
    {   1,   4, 0xFD4 }, {   6,  12, 0x6AE }, {  19,   4, 0xFD4 },   // row 16
    {   1,   4, 0xFD4 }, {   7,  10, 0x6AE }, {  19,   4, 0xFD4 },   // row 17
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 18
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 19
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 20
    {   1,   2, 0xFD4 }, {   3,  18, 0x6AE }, {  21,   2, 0xFD4 },   // row 21
    {   3,   5, 0x6AE }, {   8,   8, 0xFFF }, {  16,   5, 0x6AE },   // row 22
    {   3,   2, 0x6AE }, {   5,  14, 0xFFF }, {  19,   2, 0x6AE },   // row 23
    {   3,  18, 0xFFF },   // row 24
    {   2,  20, 0xFFF },   // row 25
    {   2,  20, 0xFFF },   // row 26
    {   2,  20, 0xFFF },   // row 27
    {   2,  20, 0xFFF },   // row 28
    {   3,   5, 0xFFF }, {   8,   8, 0x6AE }, {  16,   5, 0xFFF },   // row 29
    {   5,   2, 0xFFF }, {   7,  10, 0x000 }, {  17,   2, 0xFFF },   // row 30
    {   7,  10, 0x000 },   // row 31
};
inline constexpr SpriteRow SMURFETTE_WALK1_ROWS[] = {
    {   0,  0 },
    {   0,  1 },
    {   1,  1 },
    {   2,  1 },
    {   3,  1 },
    {   4,  1 },
    {   5,  1 },
    {   6,  3 },
    {   9,  3 },
    {  12,  3 },
    {  15,  1 },
    {  16,  5 },
    {  21,  5 },
    {  26,  5 },
    {  31,  3 },
    {  34,  3 },
    {  37,  3 },
    {  40,  3 },
    {  43,  3 },
    {  46,  3 },
    {  49,  3 },
    {  52,  3 },
    {  55,  3 },
    {  58,  3 },
    {  61,  1 },
    {  62,  1 },
    {  63,  1 },
    {  64,  1 },
    {  65,  1 },
    {  66,  3 },
    {  69,  3 },
    {  72,  1 },
};
inline constexpr SpriteFrame SMURFETTE_WALK1 = { "smurfette_walk1", 24, 32, 5, SMURFETTE_WALK1_ROWS, SMURFETTE_WALK1_SPANS };

// bat_flap0 — 24x16, 30 spans, worst row 5
inline constexpr SpriteSpan BAT_FLAP0_SPANS[] = {
    {   2,   6, 0x637 }, {  16,   6, 0x637 },   // row 1
    {   0,  10, 0x637 }, {  10,   1, 0x425 }, {  13,   1, 0x425 }, {  14,  10, 0x637 },   // row 2
    {   0,  11, 0x637 }, {  13,  11, 0x637 },   // row 3
    {   0,  11, 0x637 }, {  11,   2, 0x425 }, {  13,  11, 0x637 },   // row 4
    {   0,  10, 0x637 }, {  10,   4, 0x425 }, {  14,  10, 0x637 },   // row 5
    {   2,   6, 0x637 }, {   9,   6, 0x425 }, {  16,   6, 0x637 },   // row 6
    {   8,   2, 0x425 }, {  10,   1, 0xFFF }, {  11,   2, 0x425 }, {  13,   1, 0xFFF }, {  14,   2, 0x425 },   // row 7
    {   8,   8, 0x425 },   // row 8
    {   8,   8, 0x425 },   // row 9
    {   8,   8, 0x425 }, {  23,   1, 0x637 },   // row 10
    {   9,   6, 0x425 }, {  23,   1, 0x637 },   // row 11
    {   9,   6, 0x425 },   // row 12
    {  10,   4, 0x425 },   // row 13
};
inline constexpr SpriteRow BAT_FLAP0_ROWS[] = {
    {   0,  0 },
    {   0,  2 },
    {   2,  4 },
    {   6,  2 },
    {   8,  3 },
    {  11,  3 },
    {  14,  3 },
    {  17,  5 },
    {  22,  1 },
    {  23,  1 },
    {  24,  2 },
    {  26,  2 },
    {  28,  1 },
    {  29,  1 },
    {  30,  0 },
    {  30,  0 },
};
inline constexpr SpriteFrame BAT_FLAP0 = { "bat_flap0", 24, 16, 5, BAT_FLAP0_ROWS, BAT_FLAP0_SPANS };

// bat_flap1 — 24x16, 32 spans, worst row 5
inline constexpr SpriteSpan BAT_FLAP1_SPANS[] = {
    {   9,   2, 0x425 }, {  13,   2, 0x425 },   // row 2
    {   0,   1, 0x637 }, {   9,   2, 0x425 }, {  13,   2, 0x425 },   // row 3
    {   0,   1, 0x637 }, {   9,   6, 0x425 },   // row 4
    {   9,   6, 0x425 },   // row 5
    {   9,   6, 0x425 },   // row 6
    {   8,   2, 0x425 }, {  10,   1, 0xFFF }, {  11,   2, 0x425 }, {  13,   1, 0xFFF }, {  14,   2, 0x425 },   // row 7
    {   2,   6, 0x637 }, {   8,   8, 0x425 }, {  16,   6, 0x637 },   // row 8
    {   0,  10, 0x637 }, {  10,   4, 0x425 }, {  14,  10, 0x637 },   // row 9
    {   0,  11, 0x637 }, {  11,   2, 0x425 }, {  13,  11, 0x637 },   // row 10
    {   0,  11, 0x637 }, {  11,   2, 0x425 }, {  13,  11, 0x637 },   // row 11
    {   0,  10, 0x637 }, {  10,   4, 0x425 }, {  14,  10, 0x637 },   // row 12
    {   2,   6, 0x637 }, {  10,   4, 0x425 }, {  16,   6, 0x637 },   // row 13
};
inline constexpr SpriteRow BAT_FLAP1_ROWS[] = {
    {   0,  0 },
    {   0,  0 },
    {   0,  2 },
    {   2,  3 },
    {   5,  2 },
    {   7,  1 },
    {   8,  1 },
    {   9,  5 },
    {  14,  3 },
    {  17,  3 },
    {  20,  3 },
    {  23,  3 },
    {  26,  3 },
    {  29,  3 },
    {  32,  0 },
    {  32,  0 },
};
inline constexpr SpriteFrame BAT_FLAP1 = { "bat_flap1", 24, 16, 5, BAT_FLAP1_ROWS, BAT_FLAP1_SPANS };

// fence — 32x40, 122 spans, worst row 4
inline constexpr SpriteSpan FENCE_SPANS[] = {
    {   3,   7, 0x642 }, {  22,   7, 0x642 },   // row 0
    {   3,   7, 0x642 }, {  22,   7, 0x642 },   // row 1
    {   3,   7, 0x642 }, {  22,   7, 0x642 },   // row 2
    {   3,   7, 0x642 }, {  22,   7, 0x642 },   // row 3
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 4
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 5
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 6
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 7
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 8
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 9
    {   0,  32, 0x963 },   // row 10
    {   0,  32, 0x963 },   // row 11
    {   0,  32, 0x963 },   // row 12
    {   0,  32, 0x963 },   // row 13
    {   0,  32, 0x642 },   // row 14
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 15
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 16
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 17
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 18
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 19
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 20
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 21
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 22
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 23
    {   0,  32, 0x963 },   // row 24
    {   0,  32, 0x963 },   // row 25
    {   0,  32, 0x963 },   // row 26
    {   0,  32, 0x963 },   // row 27
    {   0,  32, 0x642 },   // row 28
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 29
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 30
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 31
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 32
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 33
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 34
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 35
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 36
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 37
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 38
    {   3,   5, 0x963 }, {   8,   2, 0x642 }, {  22,   5, 0x963 }, {  27,   2, 0x642 },   // row 39
};
inline constexpr SpriteRow FENCE_ROWS[] = {
    {   0,  2 },
    {   2,  2 },
    {   4,  2 },
    {   6,  2 },
    {   8,  4 },
    {  12,  4 },
    {  16,  4 },
    {  20,  4 },
    {  24,  4 },
    {  28,  4 },
    {  32,  1 },
    {  33,  1 },
    {  34,  1 },
    {  35,  1 },
    {  36,  1 },
    {  37,  4 },
    {  41,  4 },
    {  45,  4 },
    {  49,  4 },
    {  53,  4 },
    {  57,  4 },
    {  61,  4 },
    {  65,  4 },
    {  69,  4 },
    {  73,  1 },
    {  74,  1 },
    {  75,  1 },
    {  76,  1 },
    {  77,  1 },
    {  78,  4 },
    {  82,  4 },
    {  86,  4 },
    {  90,  4 },
    {  94,  4 },
    {  98,  4 },
    { 102,  4 },
    { 106,  4 },
    { 110,  4 },
    { 114,  4 },
    { 118,  4 },
};
inline constexpr SpriteFrame FENCE = { "fence", 32, 40, 4, FENCE_ROWS, FENCE_SPANS };

inline constexpr const SpriteFrame *SPRITE_FRAMES[] = {
    &SMURF_WALK0,
    &SMURF_WALK1,
    &SMURF_JUMP,
    &SMURF_DUCK,
    &SMURF_DEATH,
    &SMURFETTE_WALK0,
    &SMURFETTE_WALK1,
    &BAT_FLAP0,
    &BAT_FLAP1,
    &FENCE,
};
inline constexpr int SPRITE_FRAME_COUNT = 10;
