#!/bin/bash
# m68k-g++ wrapper
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec podman run --platform linux/amd64 --rm \
    -v "$(dirname "$SCRIPT_DIR"):/work" \
    -w "/work/$(basename "$SCRIPT_DIR")" \
    -u "$(id -u):$(id -g)" \
    m68k-toolchain \
    /opt/m68k-unknown-elf/bin/m68k-unknown-elf-objdump "$@"
